apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kcong
  labels:
    io.kompose.service: minio-claim0
  name: minio-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
