apiVersion: v1
kind: Service
metadata:
  namespace: kcong
  labels:
    io.kompose.service: minio
  name: minio
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: minio
status:
  loadBalancer: {}
